AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  backend-aws

  SAM Template for weather forecast endpoint

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  WeatherForecastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: weather-forecast/
      Handler: index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        WeatherForecast:
          Type: Api
          Properties:
            Path: /api/forecast
            Method: get

Outputs:
  WeatherForecastApi:
    Description: "API Gateway endpoint URL for Prod stage for Weather Forecast function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/forecast"
  WeatherForecastFunction:
    Description: "Weather Forecast Lambda Function ARN"
    Value: !GetAtt WeatherForecastFunction.Arn
  WeatherForecastFunctionIamRole:
    Description: "Implicit IAM Role created for Weather Forecast function"
    Value: !GetAtt WeatherForecastFunctionRole.Arn
